# Generated by Django 3.1 on 2021-09-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210917_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Things',
        ),
    ]
