# Generated by Django 3.1 on 2021-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='vilage',
            field=models.CharField(max_length=200),
        ),
    ]
