# Generated by Django 3.1 on 2021-09-18 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200, verbose_name='Place')),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=700)),
                ('speaker', models.CharField(max_length=100)),
                ('enterprise', models.CharField(max_length=100)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('more_info', models.FileField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
