# Generated by Django 3.1 on 2021-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210918_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
