# Generated by Django 3.1 on 2021-09-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcenter',
            options={'ordering': ['id']},
        ),
    ]
