# Generated by Django 3.1 on 2021-09-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210924_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcenter',
            options={},
        ),
    ]
