# Generated by Django 3.1 on 2021-09-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20210924_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcenter',
            options={},
        ),
    ]
