# Generated by Django 3.1 on 2021-09-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20210924_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcenter',
            options={'ordering': ['-city']},
        ),
    ]
