# Generated by Django 3.1 on 2021-09-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemd',
            options={},
        ),
    ]
