# Generated by Django 3.1 on 2021-09-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20210924_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itema',
            options={'ordering': ['created', 'title']},
        ),
    ]
