# Generated by Django 3.1 on 2021-09-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20210924_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itema',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='itemb',
            options={'ordering': ['-created', 'updated', 'title']},
        ),
        migrations.AlterModelOptions(
            name='itemc',
            options={'ordering': ['-created', 'updated', 'title']},
        ),
        migrations.AlterModelOptions(
            name='itemd',
            options={'ordering': ['-created', 'updated', 'title']},
        ),
    ]
