# Generated by Django 3.1 on 2021-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20210924_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='itema',
            name='date',
            field=models.DateField(default='not available'),
        ),
    ]
