# Generated by Django 3.1 on 2021-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_itema_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itema',
            name='date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
