# Generated by Django 3.1 on 2021-09-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_auto_20210924_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itema',
            name='date',
        ),
    ]
