# Generated by Django 3.1 on 2021-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20210919_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='amenity',
            field=models.ManyToManyField(related_name='amenity', to='enroll.Amenity'),
        ),
    ]
