# Generated by Django 3.1 on 2021-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('authore', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['authore', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30)),
                ('publication', models.ManyToManyField(to='enroll.Publication')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
