# Generated by Django 3.1 on 2021-09-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authore',
        ),
    ]
