# Generated by Django 3.1 on 2021-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_mark_table',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
