# Generated by Django 3.1 on 2021-09-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_phone',
            field=models.IntegerField(),
        ),
    ]
