# Generated by Django 3.1 on 2021-09-25 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enroll.student')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('enroll.student',),
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
