# Generated by Django 3.1 on 2021-09-25 09:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyStudent',
        ),
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enroll.student',),
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
